### ISSUE TITLE
Cannot create new dashboards on http://metrics.theodi.org/ due to crash

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/bothan#272]
### Expected Behaviour

I should be able to navigate to dashboards/create and create a dashboard

### Current Behaviour (for problems)
navigating to dashboards/create causes a 500 error. Below is the output from the logs
```
2017-08-09T09:42:54.860491+00:00 heroku[router]: at=info method=GET path="/dashboards/new" host=odi-metrics-api.herokuapp.com request_id=592ac023-8c90-418e-a9c4-8cb36cf0d201 fwd="62.254.247.131" dyno=web.1 connect=0ms service=2484ms status=500 bytes=248 protocol=https
2017-08-09T09:42:54.859313+00:00 app[web.1]: 2017-08-09 09:42:54 - NoMethodError - undefined method `[]' for nil:NilClass:
2017-08-09T09:42:54.859333+00:00 app[web.1]: 	/app/lib/bothan/helpers/metrics_helpers.rb:156:in `guess_type'
2017-08-09T09:42:54.859336+00:00 app[web.1]: 	/app/lib/bothan/helpers/metrics_helpers.rb:145:in `visualisation_type'
2017-08-09T09:42:54.859337+00:00 app[web.1]: 	/app/lib/bothan/helpers/metrics_helpers.rb:171:in `get_settings'
2017-08-09T09:42:54.859339+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:66:in `block (2 levels) in singleton class'
2017-08-09T09:42:54.859340+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:65:in `each'
2017-08-09T09:42:54.859341+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:65:in `block in singleton class'
2017-08-09T09:42:54.859342+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:-6:in `instance_eval'
2017-08-09T09:42:54.859343+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:-6:in `singleton class'
2017-08-09T09:42:54.859344+00:00 app[web.1]: 	/app/lib/bothan/../views/dashboards/new.erb:-9:in `__tilt_70315083321220'
2017-08-09T09:42:54.859346+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
2017-08-09T09:42:54.859348+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
2017-08-09T09:42:54.859349+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
2017-08-09T09:42:54.859350+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:839:in `render'
2017-08-09T09:42:54.859352+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:682:in `erb'
2017-08-09T09:42:54.859353+00:00 app[web.1]: 	/app/lib/bothan/dashboards.rb:20:in `block in registered'
```
I think this is related to the `guess_type` method crashing due to the presence of a tasklist in the total number of metrics available to to this particular Bothan instance. That's the only thing that distinguishes the http://metrics.theodi.org/ instance from other similar instances.
The errors in above output relate to 
https://github.com/theodi/bothan/blob/master/lib/views/dashboards/new.erb#L65-L66
then
https://github.com/theodi/bothan/blob/master/lib/bothan/helpers/metrics_helpers.rb#L156-L157

### Steps to Reproduce (for problems)
> Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1. navigate to https://odi-metrics-api.herokuapp.com (NB - it must be this address for the heroku logs to provide the above information
2. Log in to the bothan instance
3. Click create dashboard in nav bar (or navigate to https://odi-metrics-api.herokuapp.com/dashboards/new)
4. you should get internal server error, 500

### Your Environment
Operating System - Macintosh OS X 10.12.5
Screen Resolution - 1920 x 1080
Web Browser - Chrome 59.0.3071.115
Browser Size - 1919 x 902
IP Address - 62.254.247.131
Javascript - Enabled
Flash Version - Not Installed
Cookies - Enabled

**Comment by quadrophobiac** [comment]
@Floppy & @pezholio can I ask for your opinion on my hunch - does this look like the presence of tasklist metrics on the Metrics.theodi.org instance could be causing this error?

**Comment by Floppy** [comment]
Yep, that's definitely tasklist related.

**Comment by Floppy** [comment]
looks like it's a tasklist with an empty array. `data[:value].first[:progress]` on line 156 is exploding, so `first` is probably nil.

**Comment by Floppy** [comment]
Are there any other situations where `data[:value]` would be an array other than a task list? Is the second check necessary?

**Comment by Floppy** [comment]
maybe chart I guess.

**Comment by Floppy** [comment]
#278 fixes empty array handling and defaults to chart view, as do other null/empty value types.
